# -*- coding: utf-8 -*-
"""Covid Data analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1efPZfXd4u3HM0Qehi7nzuhE9SnMBIGWe

Data Preparation
"""

import pandas as pd
import numpy as np
import seaborn as sns

"""Importing Data

"""

url = 'https://covid.ourworldindata.org/data/owid-covid-data.csv'
df = pd.read_csv(url)
df.head()

"""Getting to Know my Datashee"""

#describe my data
df.describe()

#shape my data set
df.shape

"""Handling Duplicates"""

#check duplicated
df.duplicated().sum()
df.drop_duplicates(inplace=True)

"""Handling Null Values"""

#check null values
df.isnull().sum()

"""Dropping Nulls"""

#drop nulls
df.dropna(inplace=True)
#dropping a specific column
df1 = df.dropna(subset=['total_cases'])

"""Imputation"""

#Numerical Values
#using mean
df['total_cases'] = df['total_cases'].fillna(df['total_cases'].mean())
#using median
df['total_cases'] = df['total_cases'].fillna(df['total_cases'].median())
#Now use median to impute null values

#Categorical Values
#Select any Column with Categorical Values, impute using mode
df['continent'] = df['continent'].fillna(df['continent'].mode())

"""Dropping Columns"""

#drop column named iso_code
df.drop('iso_code', axis=1, inplace=True)
#drop column named new_deaths_smoothed
df.drop('new_deaths_smoothed', axis=1, inplace=True )

"""Creating a subset"""

#subset of data for Zimbabwe and Rwanda
subset = df[(df['location'] == 'Zimbabwe') | (df['location'] == 'Rwanda')]
#displaying the first few rows of subset
subset.head()

"""Let's save our cleaned up data"""

#saving the data
df.to_csv('url')